"""user_group is unique

Revision ID: 0f5891d84b40
Revises: 15b3a5fd98cc
Create Date: 2025-02-09 21:56:27.844814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f5891d84b40"
down_revision: Union[str, None] = "15b3a5fd98cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user_group_table", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_group_table", type_="unique")
    # ### end Alembic commands ###
